### ISSUE TITLE
My Anime channel in Plex android app mobile mode crashes at launch

### ISSUE THREAD

**Issue by pmcthor777** [japanesemediamanager/ShokoOnPlex#26]
My Anime channel crashes immediately after launch on Android OS. Issue exists on Samsung Note 3 and. Note 10.1 through the Plex app in mobile mode.  Switching the Plex app to TV mode is a workaround.

**Comment by maxpiva** [comment]
Will be fixed in the next version of JMM Server (3.6)

**Comment by pmcthor777** [comment]
Thanks for the udpate!

**Comment by pmcthor777** [comment]
Just updated to v3.6.0.2 and issue still exists. My Anime channel still crashes Plex app in mobile layout. Works fine in TV mode.

**Comment by dasco144** [comment]
I am also getting the same issue. I did use the fix you suggested previously @maxpiva over here [https://github.com/japanesemediamanager/JMMForPlex/issues/24#issuecomment-226805300](url) and it does seem to be working for the moment.

**Comment by ElementalCrisis** [comment]
Had the same issue on Android @maxpiva running latest versions, had to make the fix you suggested in the other thread to get it to load.

**Comment by rockbyo5** [comment]
im having the same bug, when i launch the Anime channel on plex (only happen on an android client), the app force close. i can post my logs if required, i just dont know how right now, ill take a look at it. Thanks for the sweet software you are developing,.

**Comment by Cazzar** [comment]
This would have been resolved by 71f042e8ee1d2e678671c00f0d79291adb7350b7
