### ISSUE TITLE
Show Episode Number Next To Episode Name

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/ShokoOnPlex#30]
As the title says, currently we only see the episode name but not the episode number. Not a problem for smaller series but for larger ones I usually remember the last episode number, not the name.

**Comment by Cazzar** [comment]
Seems on android client there is the subtitle of: "Episode N"
Windows 10 native client, doesn't show any subtitles.
Plex windows client seems to show "<Anime Title>\n Sn En"
OpenPHT shows the title and date.


Probably best to add a generic "n. <title>"

**Comment by Cazzar** [comment]
![image](https://cloud.githubusercontent.com/assets/994214/22066380/decf38ea-dde0-11e6-81c2-ce39ad3e05ac.png)
