### ISSUE TITLE
Wrong Images Being Displayed

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/ShokoOnPlex#33]
![firefox_2016-10-19_14-32-19](https://cloud.githubusercontent.com/assets/9443295/19538438/e1d6cb4a-9608-11e6-9b47-59df564312a1.png)

It seems the episode and series images being displayed are random ones from your collection, not the ones that match the series or episode being viewed.

**Comment by maxpiva** [comment]
This, sometimes depends on the client in question :(
Check if possible on ios and android.

**Comment by ElementalCrisis** [comment]
Check on Android, looks fine, Seems to be an issue only on browser client.

**Comment by Cazzar** [comment]
Looking at web, android, windows 10 and Plex Media Player all seem to be showing @ElementalCrisis still experiencing this side of things?

**Comment by ElementalCrisis** [comment]
Issues has been fixed.
