### ISSUE TITLE
filters dont load at all on the "new" win10 app

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/ShokoOnPlex#34]
as the title says, filters dont load at all on the "new" win10 app. 
dont see anything in the log about it either for the plugin.

**Comment by ElementalCrisis** [comment]
Hmm, just tried and it works for me. 

![image](https://cloud.githubusercontent.com/assets/9443295/20653064/8ab26bf4-b4bb-11e6-99d5-c0944e659520.png)

Try deleting and re-adding the plugin. I also had to be signed it for it to work.

**Comment by AreFinstad** [comment]
did you manage to load any of them tho? cause i cant. i can see the filters but not load them.

**Comment by AreFinstad** [comment]
did you manage to load any of them tho? cause i cant. i can see the filters but not load them.

the only ones i can seem to load is tags and years which comes with the server. loading all or any filter does not work.

![](https://puu.sh/sxMMZ/e69850c613.png)


anything else leads to an error. 

here is the logs: https://puu.sh/sxMIJ/f2609c22cc.zip

**Comment by Cazzar** [comment]
@AreFinstad is this still occuring with the latest version of ShokoServer? 

If so, what is the output of things like: http://localhost:8111/JMMServerPlex/GetMetadata/1/0/1550/7496232A9A70B4376F4157801071D0C2

**Comment by AreFinstad** [comment]
this seems to be fixed in the newest versions
