### ISSUE TITLE
multiple issues with open plex home theater

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/ShokoOnPlex#35]
episode info does not display at all on any file.
it seems like no matter what, it will not load info for the file itself. it does show info before you choose the episode though!

on some layouts it shows the hash or link to the file or series itself instead of the series/group name.

playback in itself works smoothly though!

NOTES on plex home theater and its open version:
its technically a fork of kodi and is pretty much the same thing. im sure some people might use it still for something.

**Comment by Surround-Sound** [comment]
Any fix?

**Comment by Cazzar** [comment]
Since I cannot find a download for PHT, (and it is officially unsupported by Plex). 
RasPlex/OpenPHT seems to be playing and loading files fine.

![openpht_2017-01-18_23-00-51](https://cloud.githubusercontent.com/assets/994214/22063262/ff359b60-ddd1-11e6-95eb-68547bb49d1d.jpg)

**Comment by Cazzar** [comment]
Use https://github.com/RasPlex/OpenPHT as Plex Home Theater is unsupported
